# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Config_Users_pb2 as Config__Users__pb2


class RouteGuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/users_db.RouteGuide/Login',
                request_serializer=Config__Users__pb2.LoginRequest.SerializeToString,
                response_deserializer=Config__Users__pb2.LoginReply.FromString,
                )
        self.SearchUser = channel.unary_unary(
                '/users_db.RouteGuide/SearchUser',
                request_serializer=Config__Users__pb2.Data.SerializeToString,
                response_deserializer=Config__Users__pb2.DataUser.FromString,
                )
        self.RegisterUser = channel.unary_unary(
                '/users_db.RouteGuide/RegisterUser',
                request_serializer=Config__Users__pb2.DataUser.SerializeToString,
                response_deserializer=Config__Users__pb2.Data.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/users_db.RouteGuide/UpdateUser',
                request_serializer=Config__Users__pb2.DataUser_Update.SerializeToString,
                response_deserializer=Config__Users__pb2.Data.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/users_db.RouteGuide/DeleteUser',
                request_serializer=Config__Users__pb2.Data.SerializeToString,
                response_deserializer=Config__Users__pb2.Data.FromString,
                )


class RouteGuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=Config__Users__pb2.LoginRequest.FromString,
                    response_serializer=Config__Users__pb2.LoginReply.SerializeToString,
            ),
            'SearchUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchUser,
                    request_deserializer=Config__Users__pb2.Data.FromString,
                    response_serializer=Config__Users__pb2.DataUser.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=Config__Users__pb2.DataUser.FromString,
                    response_serializer=Config__Users__pb2.Data.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=Config__Users__pb2.DataUser_Update.FromString,
                    response_serializer=Config__Users__pb2.Data.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=Config__Users__pb2.Data.FromString,
                    response_serializer=Config__Users__pb2.Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users_db.RouteGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteGuide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users_db.RouteGuide/Login',
            Config__Users__pb2.LoginRequest.SerializeToString,
            Config__Users__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users_db.RouteGuide/SearchUser',
            Config__Users__pb2.Data.SerializeToString,
            Config__Users__pb2.DataUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users_db.RouteGuide/RegisterUser',
            Config__Users__pb2.DataUser.SerializeToString,
            Config__Users__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users_db.RouteGuide/UpdateUser',
            Config__Users__pb2.DataUser_Update.SerializeToString,
            Config__Users__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/users_db.RouteGuide/DeleteUser',
            Config__Users__pb2.Data.SerializeToString,
            Config__Users__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
