# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Config_Users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43onfig_Users.proto\x12\x08users_db\"3\n\x0cLoginRequest\x12\x11\n\tmatricule\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"*\n\nLoginReply\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"\x80\x01\n\x08\x44\x61taUser\x12\x11\n\tmatricule\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tfull_Name\x18\x03 \x01(\t\x12\x0c\n\x04mail\x18\x04 \x01(\t\x12\x11\n\tdirection\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\t\"\xa2\x01\n\x0f\x44\x61taUser_Update\x12\x15\n\rold_matricule\x18\x01 \x01(\t\x12\x15\n\rnew_matricule\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x11\n\tfull_Name\x18\x04 \x01(\t\x12\x0c\n\x04mail\x18\x05 \x01(\t\x12\x11\n\tdirection\x18\x06 \x01(\t\x12\r\n\x05phone\x18\x07 \x01(\t\x12\x0c\n\x04role\x18\x08 \x01(\t\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x9a\x02\n\nRouteGuide\x12\x37\n\x05Login\x12\x16.users_db.LoginRequest\x1a\x14.users_db.LoginReply\"\x00\x12\x32\n\nSearchUser\x12\x0e.users_db.Data\x1a\x12.users_db.DataUser\"\x00\x12\x34\n\x0cRegisterUser\x12\x12.users_db.DataUser\x1a\x0e.users_db.Data\"\x00\x12\x39\n\nUpdateUser\x12\x19.users_db.DataUser_Update\x1a\x0e.users_db.Data\"\x00\x12.\n\nDeleteUser\x12\x0e.users_db.Data\x1a\x0e.users_db.Data\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Config_Users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=32
  _LOGINREQUEST._serialized_end=83
  _LOGINREPLY._serialized_start=85
  _LOGINREPLY._serialized_end=127
  _DATAUSER._serialized_start=130
  _DATAUSER._serialized_end=258
  _DATAUSER_UPDATE._serialized_start=261
  _DATAUSER_UPDATE._serialized_end=423
  _DATA._serialized_start=425
  _DATA._serialized_end=445
  _ROUTEGUIDE._serialized_start=448
  _ROUTEGUIDE._serialized_end=730
# @@protoc_insertion_point(module_scope)
