// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: Config_Encryption.proto

package grpc_encryption

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Config_Encryption_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Config_Encryption_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Config_Encryption_proto_rawDescGZIP(), []int{0}
}

type KeysRSA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey  string `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *KeysRSA) Reset() {
	*x = KeysRSA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Config_Encryption_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeysRSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRSA) ProtoMessage() {}

func (x *KeysRSA) ProtoReflect() protoreflect.Message {
	mi := &file_Config_Encryption_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRSA.ProtoReflect.Descriptor instead.
func (*KeysRSA) Descriptor() ([]byte, []int) {
	return file_Config_Encryption_proto_rawDescGZIP(), []int{1}
}

func (x *KeysRSA) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *KeysRSA) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

var File_Config_Encryption_proto protoreflect.FileDescriptor

var file_Config_Encryption_proto_rawDesc = []byte{
	0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x47, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x53, 0x41, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x32, 0x4e, 0x0a, 0x0a,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x53, 0x41, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x53, 0x41, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x51, 0x4c, 0x2d, 0x41, 0x75, 0x74, 0x68, 0x2d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Config_Encryption_proto_rawDescOnce sync.Once
	file_Config_Encryption_proto_rawDescData = file_Config_Encryption_proto_rawDesc
)

func file_Config_Encryption_proto_rawDescGZIP() []byte {
	file_Config_Encryption_proto_rawDescOnce.Do(func() {
		file_Config_Encryption_proto_rawDescData = protoimpl.X.CompressGZIP(file_Config_Encryption_proto_rawDescData)
	})
	return file_Config_Encryption_proto_rawDescData
}

var file_Config_Encryption_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Config_Encryption_proto_goTypes = []interface{}{
	(*Empty)(nil),   // 0: grpc_encryption.Empty
	(*KeysRSA)(nil), // 1: grpc_encryption.KeysRSA
}
var file_Config_Encryption_proto_depIdxs = []int32{
	0, // 0: grpc_encryption.RouteGuide.GetKeysRSA:input_type -> grpc_encryption.Empty
	1, // 1: grpc_encryption.RouteGuide.GetKeysRSA:output_type -> grpc_encryption.KeysRSA
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Config_Encryption_proto_init() }
func file_Config_Encryption_proto_init() {
	if File_Config_Encryption_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Config_Encryption_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Config_Encryption_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeysRSA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Config_Encryption_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Config_Encryption_proto_goTypes,
		DependencyIndexes: file_Config_Encryption_proto_depIdxs,
		MessageInfos:      file_Config_Encryption_proto_msgTypes,
	}.Build()
	File_Config_Encryption_proto = out.File
	file_Config_Encryption_proto_rawDesc = nil
	file_Config_Encryption_proto_goTypes = nil
	file_Config_Encryption_proto_depIdxs = nil
}
