// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DataChiper struct {
	PublicKey  string `json:"publicKey"`
	DataChiper string `json:"dataChiper"`
}

type DataUser struct {
	Matricule string `json:"matricule"`
	FullName  string `json:"full_name"`
	Mail      string `json:"mail"`
	Direction string `json:"direction"`
	Phone     string `json:"phone"`
	Role      string `json:"role"`
	PublicKey string `json:"publicKey"`
}

type DataUserInput struct {
	Matricule string `json:"matricule"`
	Password  string `json:"password"`
	FullName  string `json:"full_name"`
	Mail      string `json:"mail"`
	Direction string `json:"direction"`
	Phone     string `json:"phone"`
	Role      string `json:"role"`
	PublicKey string `json:"publicKey"`
}

type DataUserUpdateInput struct {
	OldMatricule string `json:"old_matricule"`
	NewMatricule string `json:"new_matricule"`
	Password     string `json:"password"`
	FullName     string `json:"full_name"`
	Mail         string `json:"mail"`
	Direction    string `json:"direction"`
	Phone        string `json:"phone"`
	Role         string `json:"role"`
	PublicKey    string `json:"publicKey"`
}

type Result struct {
	Result string `json:"result"`
}
